# frozen_string_literal: true

# Defines some specific CIDRs here. Faker is not good enough at giving private CIDRs, since you want
# space in it to put some subnets. So we have a bunch of possible ones, in /24
VPC_CIDRS = (0..255).map { |i| "10.0.#{i}.0/24" }

INSTANCE_TYPE_T2_MICRO = 't2.micro'
INSTANCE_TYPE_T2_MEDIUM = 't2.medium'
INSTANCE_TYPE_M5_LARGE = 'm5.large'
INSTANCE_TYPE_C5_9XLARGE = 'c5.9xlarge'

INSTANCE_TYPES = [
  INSTANCE_TYPE_T2_MICRO,
  INSTANCE_TYPE_T2_MEDIUM,
  INSTANCE_TYPE_M5_LARGE,
  INSTANCE_TYPE_C5_9XLARGE
].freeze

INSTANCE_STATE_PENDING = 'pending'
INSTANCE_STATE_PENDING_CODE = 0
INSTANCE_STATE_RUNNING = 'running'
INSTANCE_STATE_RUNNING_CODE = 16
INSTANCE_STATE_SHUTTING_DOWN = 'shutting-down'
INSTANCE_STATE_SHUTTING_DOWN_CODE = 32
INSTANCE_STATE_TERMINATED = 'terminated'
INSTANCE_STATE_TERMINATED_CODE = 48
INSTANCE_STATE_STOPPING = 'stopping'
INSTANCE_STATE_STOPPING_CODE = 64
INSTANCE_STATE_STOPPED = 'stopped'
INSTANCE_STATE_STOPPED_CODE = 80

INSTANCE_STATES = [
  { code: INSTANCE_STATE_PENDING_CODE, name: INSTANCE_STATE_PENDING },
  { code: INSTANCE_STATE_RUNNING_CODE, name: INSTANCE_STATE_RUNNING },
  { code: INSTANCE_STATE_SHUTTING_DOWN_CODE, name: INSTANCE_STATE_SHUTTING_DOWN },
  { code: INSTANCE_STATE_TERMINATED_CODE, name: INSTANCE_STATE_TERMINATED },
  { code: INSTANCE_STATE_STOPPING_CODE, name: INSTANCE_STATE_STOPPING },
  { code: INSTANCE_STATE_STOPPED_CODE, name: INSTANCE_STATE_STOPPED }
].freeze
