# frozen_string_literal: true

# Defines some specific CIDRs here. Faker is not good enough at giving private CIDRs, since you want
# space in it to put some subnets. So we have a bunch of possible ones, in /24
VPC_CIDRS = (0..255).map { |i| "10.0.#{i}.0/24" }

INSTANCE_TYPE_T2_MICRO = 't2.micro'
INSTANCE_TYPE_T2_MEDIUM = 't2.medium'
INSTANCE_TYPE_M5_LARGE = 'm5.large'
INSTANCE_TYPE_C5_9XLARGE = 'c5.9xlarge'

INSTANCE_TYPES = [
  INSTANCE_TYPE_T2_MICRO,
  INSTANCE_TYPE_T2_MEDIUM,
  INSTANCE_TYPE_M5_LARGE,
  INSTANCE_TYPE_C5_9XLARGE
].freeze

INTANCE_STATE_PENDING = 'pending'
INTANCE_STATE_PENDING_CODE = 0
INTANCE_STATE_RUNNING = 'running'
INTANCE_STATE_RUNNING_CODE = 16
INTANCE_STATE_SHUTTING_DOWN = 'shutting-down'
INTANCE_STATE_SHUTTING_DOWN_CODE = 32
INTANCE_STATE_TERMINATED = 'terminated'
INTANCE_STATE_TERMINATED_CODE = 48
INTANCE_STATE_STOPPING = 'stopping'
INTANCE_STATE_STOPPING_CODE = 64
INTANCE_STATE_STOPPED = 'stopped'
INTANCE_STATE_STOPPED_CODE = 80

INSTANCE_STATES = [
  { code: INTANCE_STATE_PENDING, name: INTANCE_STATE_PENDING_CODE },
  { code: INTANCE_STATE_RUNNING, name: INTANCE_STATE_RUNNING_CODE },
  { code: INTANCE_STATE_SHUTTING_DOWN, name: INTANCE_STATE_SHUTTING_DOWN_CODE },
  { code: INTANCE_STATE_TERMINATED, name: INTANCE_STATE_TERMINATED_CODE },
  { code: INTANCE_STATE_STOPPING, name: INTANCE_STATE_STOPPING_CODE },
  { code: INTANCE_STATE_STOPPED, name: INTANCE_STATE_STOPPED_CODE }
].freeze
