AllCops:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
    - 'utils/**/*'
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - define
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $LOGGER
