AllCops:
  Exclude:
    - 'utils/**/*'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw

Style/Documentation:
  Enabled: false
